- name: Deploy Flask API
  hosts: flask_servers
  become: true  # Run tasks as root
  tasks:
    - name: Update and upgrade APT packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: true

    - name: Install required dependencies
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - virtualenv
        state: present

    - name: Clone Flask API repository
      ansible.builtin.git:
        repo: "https://github.com/patty6339/Numbers_API_HNG12.git"
        dest: "/home/ubuntu/flask_api"
        version: main
        accept_hostkey: true

    - name: Create a virtual environment for Flask
      ansible.builtin.command:
        cmd: python3 -m venv /home/ubuntu/flask_api/venv
        creates: /home/ubuntu/flask_api/venv

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: /home/ubuntu/flask_api/requirements.txt
        virtualenv: /home/ubuntu/flask_api/venv
        virtualenv_command: python3 -m venv

    - name: Create systemd service file for Flask API
      ansible.builtin.copy:
        dest: /etc/systemd/system/flask_api.service
        mode: '0644'  # Secure file permissions
        content: |
          [Unit]
          Description=Flask API Service
          After=network.target

          [Service]
          User=ubuntu
          WorkingDirectory=/home/ubuntu/flask_api
          ExecStart=/home/ubuntu/flask_api/venv/bin/python /home/ubuntu/flask_api/main.py
          Restart=always

          [Install]
          WantedBy=multi-user.target
      notify: Restart Flask API

    - name: Reload systemd to apply new service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable and start Flask API service
      ansible.builtin.systemd:
        name: flask_api
        state: started
        enabled: true

  handlers:
    - name: Restart Flask API
      ansible.builtin.systemd:
        name: flask_api
        state: restarted
